### ISSUE TITLE
Why can't raspberry Pie 4 automatically start the radar and camera after entering the system?

### ISSUE THREAD

**Issue by ddwy** [turtlebot/turtlebot4_robot#5] opened 2022-08-15 03:02 UTC
Why can't raspberry Pie 4 automatically start the radar and camera after entering the system?

**Comment by roni-kreinin** [comment] 2022-08-24 15:16
Closing as duplicate of https://github.com/turtlebot/turtlebot4/issues/25

**Closed as completed by roni-kreinin** 2022-08-24 15:16 UTC
